### ISSUE TITLE
Dropdown: Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by henrikjl** [vrk-kpa/suomifi-ui-components#720]
We've got a `Dropdown` component inside a modal and based on the value the whole modal can be unmounted and another one rendered. When this happens **for the first time** (only happens once, subsequent value changes do not produce the error) we get the `Can't perform a React state update on an unmounted component.`-error with the modified stack pasted below.

Unfortunately I couldn't reproduce this in a small example. Could be a timing issue when there are multiple hooks etc. involved.

Here's a sandbox that's similar to our setup but of course quite lacking: https://codesandbox.io/s/polished-dust-92i3j0

## Expected Behavior or Possible Solution

The Dropdown-component should handle being unmounted correctly when it's used as a controlled component.

## Actual Behavior and Screenshots

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    at BaseDropdown (http://localhost:42621/static/js/bundle.js:275995:90)
    at http://localhost:42621/static/js/bundle.js:276445:8
    at O (http://localhost:42621/static/js/bundle.js:265106:6)
    at AutoId (http://localhost:42621/static/js/bundle.js:290190:17)
    at http://localhost:42621/static/js/bundle.js:276457:22
    at OurSelectorComponent (http://localhost:42621/static/js/bundle.js:22598:68)
    at div
    at Div
    at O (http://localhost:42621/static/js/bundle.js:265106:6)
    at BaseModalContent (http://localhost:42621/static/js/bundle.js:287749:90)
    at O (http://localhost:42621/static/js/bundle.js:265106:6)
    at ModalContent
    at div
    at div
    at ModalPortal (http://localhost:42621/static/js/bundle.js:245681:5)
    at Modal (http://localhost:42621/static/js/bundle.js:245309:5)
    at BaseModal (http://localhost:42621/static/js/bundle.js:287443:90)
    at O (http://localhost:42621/static/js/bundle.js:265106:6)
    at Modal (http://localhost:42621/static/js/bundle.js:287581:29)
```

## Steps to Reproduce the Problem

Couldn't reproduce in a minimal setup. Contact me for more information if needed.

## Specifications

- Version: 10.0.0

### Environment: At least development

Using create react app

**Comment by riitasointi** [comment]
Thanks for the description! We are investigating the issue and hope to patch it in an upcoming release.

**Comment by henrikjl** [comment]
Thanks! I'll close this as the issue's been fixed 🎉
